apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPAuthzConfig
metadata:
  name: resources-access
  namespace: toolhive-demo
spec:
  type: cedarv1
  config:
    policies:
      - 'permit(principal in THVGroup::"engineering", action == Action::"call_tool", resource == Tool::"list_resources");'
      - 'permit(principal in THVGroup::"support", action == Action::"call_tool", resource == Tool::"add_issue_comment");'
      - 'permit(principal in THVGroup::"support", action == Action::"call_tool", resource == Tool::"issue_read");'
      - 'forbid(principal, action == Action::"call_tool", resource) when { principal in THVGroup::"engineering" } unless { resource in [Tool::"add_issue_comment", Tool::"issue_read"] };'
    entities_json: '[]'
    group_claim_name: groups
