// SPDX-License-Identifier: Apache-2.0

package demo

import (
	"strings"
	"testing"
)

func TestRenderToolHiveManifest(t *testing.T) {
	t.Parallel()
	source := []byte(`
// The source remains readable and editor-friendly.
permit(
  principal in THVGroup::"engineering",
  action == Action::"call_tool",
  resource == Tool::"list resources"
);
/* Remediation must remain a separate Cedar policy. */
forbid(principal in THVGroup::"support", action, resource)
unless { resource in [Tool::"issue_read", Tool::"add_issue_comment"] };
`)

	manifest, err := RenderToolHiveManifest(source)
	if err != nil {
		t.Fatalf("RenderToolHiveManifest() error = %v", err)
	}
	text := string(manifest)
	if !strings.HasPrefix(text, "# Code generated by go run ./cmd/generate-policy-manifests; DO NOT EDIT.\n") {
		t.Errorf("manifest does not have a generated-file header:\n%s", text)
	}
	for _, expected := range []string{
		`      - 'permit ( principal in THVGroup::"engineering", action == Action::"call_tool", resource == Tool::"list resources" );'`,
		`      - 'forbid ( principal in THVGroup::"support", action, resource ) unless { resource in [Tool::"issue_read", Tool::"add_issue_comment"] };'`,
		"    entities_json: '[]'",
	} {
		if !strings.Contains(text, expected) {
			t.Errorf("manifest does not contain %q:\n%s", expected, text)
		}
	}
}

func TestRenderToolHiveManifestRejectsIncompletePolicy(t *testing.T) {
	t.Parallel()
	_, err := RenderToolHiveManifest([]byte(`permit(principal, action, resource)`))
	if err == nil || !strings.Contains(err.Error(), "parse Cedar policies") {
		t.Fatalf("RenderToolHiveManifest() error = %v, want Cedar parse error", err)
	}
}

func TestRenderToolHiveManifestRejectsNoPolicies(t *testing.T) {
	t.Parallel()
	_, err := RenderToolHiveManifest([]byte(`// No policies here.`))
	if err == nil || !strings.Contains(err.Error(), "contains no policies") {
		t.Fatalf("RenderToolHiveManifest() error = %v, want empty policy set error", err)
	}
}
