// SPDX-License-Identifier: Apache-2.0

package demo

import (
	"fmt"
	"os"
	"strings"
	"unicode"
)

// RenderToolHiveManifest converts a native Cedar policy file into the
// ToolHive MCPAuthzConfig used by the live demo.
func RenderToolHiveManifest(source []byte) ([]byte, error) {
	policies, err := splitCedarPolicies(string(source))
	if err != nil {
		return nil, err
	}

	var output strings.Builder
	output.WriteString("# Code generated by go run ./cmd/generate-policy-manifests; DO NOT EDIT.\n")
	output.WriteString("apiVersion: toolhive.stacklok.dev/v1beta1\n")
	output.WriteString("kind: MCPAuthzConfig\n")
	output.WriteString("metadata:\n")
	output.WriteString("  name: resources-access\n")
	output.WriteString("  namespace: toolhive-demo\n")
	output.WriteString("spec:\n")
	output.WriteString("  type: cedarv1\n")
	output.WriteString("  config:\n")
	output.WriteString("    policies:\n")
	for _, policy := range policies {
		output.WriteString("      - '")
		output.WriteString(strings.ReplaceAll(policy, "'", "''"))
		output.WriteString("'\n")
	}
	output.WriteString("    entities_json: '[]'\n")
	output.WriteString("    group_claim_name: groups\n")
	return []byte(output.String()), nil
}

// GenerateToolHiveManifest renders source and writes or verifies output.
func GenerateToolHiveManifest(source, output string, check bool) error {
	data, err := os.ReadFile(source)
	if err != nil {
		return fmt.Errorf("read Cedar source %s: %w", source, err)
	}
	manifest, err := RenderToolHiveManifest(data)
	if err != nil {
		return fmt.Errorf("render %s: %w", source, err)
	}
	return WriteGenerated(output, manifest, check)
}

func splitCedarPolicies(source string) ([]string, error) {
	var policies []string
	var current strings.Builder
	inString := false
	escaped := false
	inLineComment := false
	inBlockComment := false

	for index := 0; index < len(source); index++ {
		character := source[index]
		next := byte(0)
		if index+1 < len(source) {
			next = source[index+1]
		}

		switch {
		case inLineComment:
			if character == '\n' {
				inLineComment = false
				current.WriteByte(' ')
			}
			continue
		case inBlockComment:
			if character == '*' && next == '/' {
				inBlockComment = false
				current.WriteByte(' ')
				index++
			}
			continue
		case inString:
			current.WriteByte(character)
			if escaped {
				escaped = false
			} else if character == '\\' {
				escaped = true
			} else if character == '"' {
				inString = false
			}
			continue
		case character == '/' && next == '/':
			inLineComment = true
			index++
			continue
		case character == '/' && next == '*':
			inBlockComment = true
			index++
			continue
		case character == '"':
			inString = true
			current.WriteByte(character)
			continue
		case character == ';':
			current.WriteByte(character)
			policy := normalizeCedarWhitespace(current.String())
			if policy != ";" {
				policies = append(policies, policy)
			}
			current.Reset()
			continue
		default:
			current.WriteByte(character)
		}
	}

	if inString {
		return nil, fmt.Errorf("unterminated Cedar string")
	}
	if inBlockComment {
		return nil, fmt.Errorf("unterminated Cedar block comment")
	}
	if strings.TrimSpace(current.String()) != "" {
		return nil, fmt.Errorf("Cedar policy is missing a trailing semicolon")
	}
	if len(policies) == 0 {
		return nil, fmt.Errorf("Cedar source contains no policies")
	}
	return policies, nil
}

func normalizeCedarWhitespace(input string) string {
	var output strings.Builder
	inString := false
	escaped := false
	pendingSpace := false

	for _, character := range input {
		if inString {
			output.WriteRune(character)
			if escaped {
				escaped = false
			} else if character == '\\' {
				escaped = true
			} else if character == '"' {
				inString = false
			}
			continue
		}
		if unicode.IsSpace(character) {
			pendingSpace = output.Len() > 0
			continue
		}
		if pendingSpace {
			output.WriteByte(' ')
			pendingSpace = false
		}
		output.WriteRune(character)
		if character == '"' {
			inString = true
		}
	}
	return strings.TrimSpace(output.String())
}
