// SPDX-License-Identifier: Apache-2.0

package demo

import (
	"fmt"
	"os"
	"strings"
	"unicode"

	cedar "github.com/cedar-policy/cedar-go"
)

// RenderToolHiveManifest converts a native Cedar policy file into the
// ToolHive MCPAuthzConfig used by the live demo.
func RenderToolHiveManifest(source []byte) ([]byte, error) {
	policySet, err := cedar.NewPolicySetFromBytes("policies.cedar", source)
	if err != nil {
		return nil, fmt.Errorf("parse Cedar policies: %w", err)
	}

	var policies []string
	for index := 0; ; index++ {
		policy := policySet.Get(cedar.PolicyID(fmt.Sprintf("policy%d", index)))
		if policy == nil {
			break
		}
		policies = append(policies, normalizeCedarWhitespace(string(policy.MarshalCedar())))
	}
	if len(policies) == 0 {
		return nil, fmt.Errorf("Cedar source contains no policies")
	}

	var output strings.Builder
	output.WriteString("# Code generated by go run ./cmd/generate-policy-manifests; DO NOT EDIT.\n")
	output.WriteString("apiVersion: toolhive.stacklok.dev/v1beta1\n")
	output.WriteString("kind: MCPAuthzConfig\n")
	output.WriteString("metadata:\n")
	output.WriteString("  name: resources-access\n")
	output.WriteString("  namespace: toolhive-demo\n")
	output.WriteString("spec:\n")
	output.WriteString("  type: cedarv1\n")
	output.WriteString("  config:\n")
	output.WriteString("    policies:\n")
	for _, policy := range policies {
		output.WriteString("      - '")
		output.WriteString(strings.ReplaceAll(policy, "'", "''"))
		output.WriteString("'\n")
	}
	output.WriteString("    entities_json: '[]'\n")
	output.WriteString("    group_claim_name: groups\n")
	return []byte(output.String()), nil
}

// GenerateToolHiveManifest renders source and writes or verifies output.
func GenerateToolHiveManifest(source, output string, check bool) error {
	data, err := os.ReadFile(source)
	if err != nil {
		return fmt.Errorf("read Cedar source %s: %w", source, err)
	}
	manifest, err := RenderToolHiveManifest(data)
	if err != nil {
		return fmt.Errorf("render %s: %w", source, err)
	}
	return WriteGenerated(output, manifest, check)
}

func normalizeCedarWhitespace(input string) string {
	var output strings.Builder
	inString := false
	escaped := false
	pendingSpace := false

	for _, character := range input {
		if inString {
			output.WriteRune(character)
			if escaped {
				escaped = false
			} else if character == '\\' {
				escaped = true
			} else if character == '"' {
				inString = false
			}
			continue
		}
		if unicode.IsSpace(character) {
			pendingSpace = output.Len() > 0
			continue
		}
		if pendingSpace {
			output.WriteByte(' ')
			pendingSpace = false
		}
		output.WriteRune(character)
		if character == '"' {
			inString = true
		}
	}
	return strings.TrimSpace(output.String())
}
