apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPAuthzConfig
metadata:
  name: resources-access
  namespace: toolhive-demo
spec:
  type: cedarv1
  config:
    policies:
      - 'permit(principal in THVGroup::"cluster-view", action == Action::"call_tool", resource == Tool::"list_resources");'
    entities_json: '[]'
    group_claim_name: groups
